create table if not exists agent(
agent_id serial primary key,
email varchar(250),
name text,
password text
);

create table if not exists client (
    client_id serial primary key,
    name text,
    phone_number integer,
    email text,
    agent_id int references agent(agent_id)
);

create table if not exists meeting_entry (
    meeting_id serial primary key,
    client_id int references client(client_id),
    date text,
    notes text,
    name text
);

create table if not exists application (
    application_id serial primary key,
    client_id int references client(client_id),
    insured_name text,
    gender text,
    dob text,
    ssn integer,
    address varchar(100),
    years_at_this_address integer,
    tel text,
    email text,
    driver_license_number integer,
    exp text,
    state text,
    us_citizens text,
    employer text,
    start_date text,
    work_address text,
    occupation text,
    duties text,
    annual_income integer,
    annual_household_income integer,
    net_worth integer,
    product_type name,
    coverage_amount integer,
    class_rating text,
    planned_premium integer,
    term_years integer,
    replacement text,
    purpose_of_insurance text,
    ltc text,
    living_benefits text,
    lifetime_income_rider text,
    other_rider text,
    pb_name text,
    pb_dob text,
    pb_ssn integer,
    pb_relationship text,
    pb2_name text,
    pb2_dob text,
    pb2_ssn integer,
    pb2_relationship text,
    con_name text,
    con_dob text,
    con_ssn integer,
    con_relationship text,
    con2_name text,
    con2_dob text,
    con2_ssn integer,
    con2_relationship text,
    height text,
    weight text,
    tobacco text,
    pb_or_cholesterol text,
    pbc_explain text,
    diabetes text,
    diabetes_explain text,
    surgery_history text,
    surgery_history_explain text,
    medication text,
    father_liv integer,
    father_dead integer,
    father_cause text,
    mother_liv integer,
    mother_dead integer,
    mother_cause text,
    sib_liv integer,
    sib_dead integer,
    sib_cause text,
    driving_history text,
    pcp_name text,
    pcp_tel text,
    pcp_address text,
    pcp_date_last text,
    pcp_reason text,
    bank_name text,
    bank_address text,
    bank_routing_number integer,
    bank_account_number integer,
    owner_name text,
    bank_dob text,
    bank_ssn integer,
    bank_address_2 text,
    bank_tel text,
    exam_scheduled_date text,
    examiner text,
    note text,
    tobacco_explain text,
    c1 text,
    c2 text,
    fa text,
    fa2 text,
    pn text,
    pn2 text,
    iy text,
    iy2 text,
    sv text,
    sv2 text,
    o text,
    o2 text 
);

